#
# SConstruct
# scons build script

# libged101core.a -	ged101 core engine library

engine = ['ged101core', 
	Split("""
	./source/DebugReport.cpp
	./source/MainSystem.cpp
	./source/GraphicsDevice.cpp
	./source/InputDevice.cpp
	./source/InputDevice_Keyboard.cpp
	./source/InputDevice_Mouse.cpp
	./source/InputDevice_Joystick.cpp
	./source/AudioDevice.cpp
	./source/Audio_OGG.cpp
	
	./source/ColorRGB.cpp
	
	./source/ImageResource.cpp
	./source/ImageList.cpp
	./source/BitmapFont.cpp
	./source/AnimationFrame.cpp
	./source/AnimationSequence.cpp
	
	./source/GameTimer.cpp
	./source/GameStateManager.cpp
	
	./source/GameObject.cpp
	./source/GameObjectGroup.cpp
	./source/GameObjectGroupManager.cpp

	./source/Tile.cpp
	./source/TileMap.cpp
	./source/TileMapRenderer.cpp
	./source/Tileset.cpp
	
	./source/NameDirectory.cpp
	./source/main.cpp
	""")]

################################################################################
# build the engine library into the lib folder
#
# engine[0] is the name of the library
# engine[1] is the list of sources to be compiled
#
################################################################################

import os
buildEnv = Environment(CCFLAGS = '-g', CPPPATH = ['../','.','./include'])
buildEnv.StaticLibrary('./lib/' + os.name + '/' + engine[0], engine[1])

################################################################################





