#
# SConstruct
# scons build script

#	./source/ALBASEMain.cpp

engine = ['engine', 
	Split("""

	./source/GraphicsDevice.cpp
	./source/InputDevice.cpp
	./source/InputDevice_Keyboard.cpp
	./source/InputDevice_Mouse.cpp
	./source/InputDevice_Joystick.cpp
	./source/AudioDevice.cpp
	./source/Audio_OGG.cpp
	./source/DebugReport.cpp
	./source/ImageResource.cpp
	./source/BitmapFont.cpp
	./source/AnimationFrame.cpp
	./source/AnimationSequence.cpp
	
	./source/Tile.cpp
	./source/TileMap.cpp
	
	./source/GameTimer.cpp
	./source/GameStateManager.cpp
	./source/main.cpp
	./source/CommunicationDevice.cpp
	./source/GameObject.cpp
	./source/GameObjectGroup.cpp
	./source/GameObjectGroupManager.cpp
	""")]

################################################################################
# build the engine library into the lib folder
#
# engine[0] is the name of the library
# engine[1] is the list of sources to be compiled
#
################################################################################

import os
buildEnv = Environment(CCFLAGS = '-g', CPPPATH = ['../','.','./include'])
buildEnv.StaticLibrary('./lib/' + os.name + '/' + engine[0], engine[1])

################################################################################





